[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL = "https://ixxswgndrpaolvoyqjwc.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4eHN3Z25kcnBhb2x2b3lxandjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MTg5MTUsImV4cCI6MjA1OTI5NDkxNX0.kd5fxwp9lxgrRQfkeBmWJ6r_etYi5K8FgGuyN_AEBVA"
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
